/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author luccas
 */
public class AtributteValueForm extends javax.swing.JFrame {

    /**
     * Creates new form AtributteValueForm
     */
    public AtributteValueForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attributeNameLabel = new javax.swing.JLabel();
        attributeTextField = new javax.swing.JTextField();
        saveAttributeButton = new javax.swing.JButton();
        deleteAttributeButton = new javax.swing.JButton();
        attributeScrollPane = new javax.swing.JScrollPane();
        attributeTable = new javax.swing.JTable();
        forAttributeLabel = new javax.swing.JLabel();
        attributeComboBox = new javax.swing.JComboBox<>();
        valueIsLabel = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();
        saveValueButton = new javax.swing.JButton();
        deleteValueButton = new javax.swing.JButton();
        valueScrollPane = new javax.swing.JScrollPane();
        valueTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        attributeNameLabel.setText("Attribute Name:");

        saveAttributeButton.setText("Save Attribute");

        deleteAttributeButton.setText("Delete Attribute");

        attributeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        attributeScrollPane.setViewportView(attributeTable);

        forAttributeLabel.setText("For Attribute");

        attributeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        valueIsLabel.setText("Value is: ");

        valueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueTextFieldActionPerformed(evt);
            }
        });

        saveValueButton.setText("Save Value");

        deleteValueButton.setText("Delete Value");

        valueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        valueScrollPane.setViewportView(valueTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valueScrollPane)
                    .addComponent(attributeScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(forAttributeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(attributeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueIsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(valueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveValueButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteValueButton)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(attributeNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(attributeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveAttributeButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteAttributeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attributeNameLabel)
                    .addComponent(attributeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveAttributeButton)
                    .addComponent(deleteAttributeButton))
                .addGap(18, 18, 18)
                .addComponent(attributeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forAttributeLabel)
                    .addComponent(attributeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueIsLabel)
                    .addComponent(valueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveValueButton)
                    .addComponent(deleteValueButton))
                .addGap(18, 18, 18)
                .addComponent(valueScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> attributeComboBox;
    private javax.swing.JLabel attributeNameLabel;
    private javax.swing.JScrollPane attributeScrollPane;
    private javax.swing.JTable attributeTable;
    private javax.swing.JTextField attributeTextField;
    private javax.swing.JButton deleteAttributeButton;
    private javax.swing.JButton deleteValueButton;
    private javax.swing.JLabel forAttributeLabel;
    private javax.swing.JButton saveAttributeButton;
    private javax.swing.JButton saveValueButton;
    private javax.swing.JLabel valueIsLabel;
    private javax.swing.JScrollPane valueScrollPane;
    private javax.swing.JTable valueTable;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration//GEN-END:variables
}
