/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import model.ActionModel;
import model.Services;
import org.jdesktop.beansbinding.Binding;

/**
 *
 * @author luccas
 */
public class RegisterActionsForm extends javax.swing.JFrame {
    
    private List<ActionModel> listAction = null;
    /**
     * Creates new form RegisterActionsForm
     */
    public RegisterActionsForm() {
        initComponents();
        listAction = Services.getActionModelList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        actionList = new java.util.ArrayList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        actionsTable = new javax.swing.JTable();
        actionNameLabel = new javax.swing.JLabel();
        actionTextField = new javax.swing.JTextField();
        saveActionButton = new javax.swing.JButton();
        deleteActionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, actionList, actionsTable, "actionTableBinding");
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${actionName}"));
        columnBinding.setColumnName("Action Name");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(actionsTable);

        actionNameLabel.setText("Action Name:");

        saveActionButton.setText("Save");
        saveActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionButtonActionPerformed(evt);
            }
        });

        deleteActionButton.setText("Delete");
        deleteActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(actionNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(actionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteActionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveActionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actionNameLabel)
                    .addComponent(actionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveActionButton))
                .addGap(18, 18, 18)
                .addComponent(deleteActionButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionButtonActionPerformed
        // Add to list a new ActionModel
        if(actionTextField.getText() == null || "".equals(actionTextField.getText()) ) {
            /*Field is void alert*/
            JOptionPane.showMessageDialog(rootPane, "Action Name is void");
        }
        else {
            /*Create action and add to list*/
            ActionModel action = new ActionModel();
            action.setActionName(actionTextField.getText());
            listAction.add(action);
            refreshTable();
            /*Clean actionTextField*/
            actionTextField.setText("");
        }
    }//GEN-LAST:event_saveActionButtonActionPerformed

    private void deleteActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionButtonActionPerformed
        // Delete selected action.
        int selectedRow = actionsTable.getSelectedRow();
        int selectedColumn = actionsTable.getSelectedColumn();
        
        /*TODO: Check if user has selected*/
        
        /*Get selected string*/
        String selectedValue = (String) actionsTable.getValueAt(selectedRow, selectedColumn);
        
        int selectedValueIndex = 0;
        for (ActionModel a : listAction) {
            if(a.getActionName().equals(selectedValue)) {
                break;
            }
            selectedValueIndex ++;
        }
        /*Delete */
        if(!listAction.isEmpty()) {
            listAction.remove(selectedValueIndex);
            refreshTable();
        }
    }//GEN-LAST:event_deleteActionButtonActionPerformed

    private void refreshTable() {
        Binding b = bindingGroup.getBinding("actionTableBinding");
        b.unbind();
        actionList.clear();
        actionList.addAll(listAction);
        b.bind();
        actionsTable.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.ArrayList<ActionModel> actionList;
    private javax.swing.JLabel actionNameLabel;
    private javax.swing.JTextField actionTextField;
    private javax.swing.JTable actionsTable;
    private javax.swing.JButton deleteActionButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveActionButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
